#!/bin/sh
param set SENS_EN_GPSSIM 0
param set SENS_EN_BAROSIM 0
param set SENS_EN_MAGSIM 0
param set SENS_EN_ARSPDSIM 0
param set CA_AIRFRAME 1
param set CA_ROTOR_COUNT 1
param set CA_ROTOR0_PX 0.3
param set CA_SV_CS_COUNT 3
param set CA_SV_CS0_TRQ_R 1
param set CA_SV_CS0_TRQ_P 0
param set CA_SV_CS0_TRQ_Y 0
param set CA_SV_CS0_TYPE 15
param set CA_SV_CS1_TRQ_R 0
param set CA_SV_CS1_TRQ_P 1
param set CA_SV_CS1_TRQ_Y 0
param set CA_SV_CS1_TYPE 3
param set CA_SV_CS2_TRQ_R 0
param set CA_SV_CS2_TRQ_P 0
param set CA_SV_CS2_TRQ_Y 1
param set CA_SV_CS2_TYPE 4
param set PWM_MAIN_FUNC1 201
param set PWM_MAIN_FUNC2 202
param set PWM_MAIN_FUNC3 203
param set PWM_MAIN_FUNC4 101
param set PWM_MAIN_FUNC5 0
param set PWM_MAIN_FUNC6 0
param set PWM_MAIN_FUNC7 0
param set PWM_MAIN_FUNC8 0
param set PWM_MAIN_FUNC9 0
param set PWM_MAIN_FUNC10 0
param set PWM_MAIN_FUNC11 0
param set PWM_MAIN_FUNC12 0
param set PWM_MAIN_FUNC13 0
param set PWM_MAIN_FUNC14 0
param set PWM_MAIN_FUNC15 0
param set PWM_MAIN_FUNC16 0
param set PWM_MAIN_REV 0
param set-default FW_THR_MAX 1
param set-default FW_THR_MIN 0
param set-default FW_THR_TRIM 0.4
param set-default TRIM_PITCH 0
param set-default FW_PSP_OFF 0
param set-default FW_AIRSPD_MIN 11
param set-default FW_AIRSPD_TRIM 15
param set-default FW_AIRSPD_MAX 25
param set-default FW_SPOILERS_LND 0
param set-default EKF2_GPS_DELAY 0
param set-default RWTO_TKOFF 1
